//
//  ClassData.swift
//  ClassRank
//
//  Created by 90304588 on 3/29/22.
//

import Foundation
import SwiftUI

class ClassData: Decodable, Identifiable, ObservableObject {
    
    var className: String
    var Teacher: String?
    var credits: Int
    var prerequisite: String
    var description: String
    
    
    init(className: String, Teacher: String, credits: Int, preR: String, description: String){
        self.className = className
        self.Teacher = Teacher
        self.credits = credits
        self.prerequisite = preR
        self.description = description
    }
}

extension Color {
    
    static let offWhite = Color(red: 243 / 255, green: 243 / 255, blue: 243 / 255)
    
}

extension GlobalVar{
    
    static let WorldLanguageClasses = [advHeritageSpanish, advSpanishImmersion3, advancedSpanish3, advancedSpanish4, apSpanishLitandCulture, americanSignLanguage1, asl2, asl3, Chinese1, chinese2, chinese3, chinese4, chinese5, french1, french2, french3, french4, french5, french6, german1, german2, german3, german4, german5, spanish1, spanish2, spanish3, spanish4, spanish5, spanish6]
    
    static let ScienceClasses = [physScience9, honorsPhys, hps, hChem, hBio, chemBlended, chem, bio, basicBio, basicphySci, basicChem, apPhys, apEnviron, apChem, apBio, advBio1, advBio2]
    
        static let physScience9 = ClassData(className: "Physical Science 9 A&B", Teacher: "", credits: 2, preR: "None", description: "Physical Science A—this course primarily explores introductory chemistry concepts. Major areas covered include atomic structure and periodicity, chemical bonding and formulas, as well as chemical reactions. Also covered in Physical Science A are methods for conducting and reporting on an individual experiment. Physical Science B—this course primarily explores introductory physics concepts. Major areas covered include conversion of units, motion, forces, and energy.  Also covered in Physical Science B is a unit on STEM (Science, Technology, Engineering, and Mathematics) concepts.")
        
        static let honorsPhys = ClassData(className: "Honors Physics A&B", Teacher: "", credits: 2, preR: "Science 9, Algebra II and enrollment in/or completion of Pre-Calculus", description: "In this course the core concepts of physics will be developed using both conceptual and mathematical models based on lab investigations, demonstrations, activities, discussion, and problem solving. The course is specifically designed for students who have a strong interest and background in science and math and will be pursuing further training in science, math, medicine or engineering at college. Most colleges and major universities recommend the completion of a physics course for admission. If you are considering a science related career, you should seriously consider taking Honors Physics. This course is a preparation for some but not all of the learning targets for the AP Physics 1 and the AP Physics C mechanics exam.")
        
        static let hps = ClassData(className: "Honors Physical Science 9 A&B", Teacher: "", credits: 2, preR: "Algebra I", description: "   Honors Physical Science 9 A&B is taught at a faster pace, goes into more depth on selected topics, and looks at some topics with a higher math emphasis than the other Physical Science 9 courses. Honors Physical Science A—this course explores introductory chemistry concepts.  Major areas covered include measurements, atomic structure and periodicity, chemical bonding and formulas, as well as chemical reactions.  Also covered in Honors Physical Science A are methods for conducting research and reporting on an individual experiment. Honors Physical Science B—this course explores introductory physics concepts. Major areas covered include conversion of units, motion, forces, and energy.  Also covered in Honors Physical Science B is a unit on STEM (Science, Technology, Engineering, and Math) concepts.")
        
        static let hChem = ClassData(className: "Honors Chemistry A&B", Teacher: "", credits: 2, preR: "Science 9 and Geometry", description: " In this course chemical principles will be approached in depth and with more of a mathematical approach. Course content includes: atomic and molecular structure, chemical reactions, energy, kinetics, equilibrium, solutions, acid/base, nuclear chemistry and organic chemistry. It is designed for students who are more abstract thinkers, have a strong math background, and are possibly considering taking college chemistry or majoring in a STEM related field. Content is accessed in part through blended/online learning with elements of student control over time, place, path and/or pace. In addition content will also be acquired through peer learning, group work, and collaborative laboratory experiments.")
        
        static let hBio = ClassData(className: "Honors Biology A&B", Teacher: "", credits: 2, preR: "Physical Science A&B or Honors Physical Science 9 A&B", description: "This is an accelerated Biology course.  Although course topics are similar to that of Biology A & B, the rigor and depth of each of those concepts is elevated. Topics of study include: biotechnology, cell structure and function, biochemistry, DNA, cell division, protein synthesis, genetics, evolution, microbiology, animal behavior, and ecology. Students enrolling in this course should be self-motivated and thrive on academic challenge. Course content is accessed in part through blended/online learning with elements of student control over time, place, path and/or pace.")
        
        static let chemBlended = ClassData(className: "Chemistry Blended", Teacher: "", credits: 2, preR: "Prerequisite: Science 9 and Algebra I", description: "This course is designed to provide an introduction to the basic principles of chemistry. Students will study introductory principles; nomenclature, writing and balancing equations, atomic structure, bonding, solutions, stoichiometry, acid/base, and chemical analysis, along with an introduction into organic chemistry. Blended / Hybrid courses are designed and delivered by EPHS staff. They offer a mix of face to face and online instruction.  Course content has elements of student control over time, place, path and/or pace with the goal of affording each student a more personalized learning experience.")
        
        static let chem = ClassData(className: "Chemistry A&B", Teacher: "", credits: 2, preR: "Science 9 and Algebra I", description: " This course is designed to provide an introduction to the basic principles of chemistry. Students will study introductory principles; nomenclature, writing and balancing equations, atomic structure, bonding, solutions, stoichiometry, acid/base, and chemical analysis, along with an introduction into organic chemistry.")
        
        static let bio = ClassData(className: "Biology A&B", Teacher: "", credits: 2, preR: "Science 9 and Algebra I", description: "Biology A - this course presents introductory information and basic skills in the area of ecology,, cell structure and function, biochemistry, DNA, cell division, and protein synthesis. Biology B - this course presents introductory information and basic skills in the area of genetics, evolution,, microbiology,, animal behavior, and biotechnology.")
        
        static let basicphySci = ClassData(className: "Basic Physical Science 9 A&B", Teacher: "", credits: 2, preR: "Teacher recommendation", description: "Basic Physical Science 9 does not go into as much depth on selected topics as Physical Science 9. Basic Physical Science A—this course explores introductory chemistry concepts.  Major areas covered include measurements, atomic structure and periodicity, chemical bonding and formulas, as well as chemical reactions. Also covered in Basic Physical Science A are methods for conducting research and reporting on an individual experiment. Basic Physical Science B—this course explores introductory physics concepts.  Major areas covered include conversion of units, motion, forces, and energy. Also covered in Basic Physical Science B is a unit on STEM (Science, Technology, Engineering, and Math) concepts.")
        
        static let basicChem = ClassData(className: "Basic Chemistry A&B", Teacher: "", credits: 2, preR: "Science 9, Algebra I", description: "Basic Chemistry is an introductory chemistry course where the amount of learning targets are different than that of Chemistry A and B. However the same essential learning targets are covered and students have the entire semester to demonstrate proficiency. If science is a difficult course for you, then basic chemistry would be a good fit. The first term of the course covers writing and naming formulas, identifying chemical reactions, and balancing chemical equations. The second term of the course covers basic mole calculations and drawing molecules.  Students will also have the opportunity of participating in a passion project during each term.")
        
        static let basicBio = ClassData(className: "Basic Biology A&B", Teacher: "", credits: 2, preR: "Any 9th grade science", description: " Basic Biology does not go into as much depth on selected topics as Biology. Biology A - this course presents introductory information and basic skills in the area of the characteristics of living things, the nature of science, ecology, cell structure and function, biochemistry, DNA, cell division, and protein synthesis. Biology B - this course presents introductory information and basic skills in the area of genetics, evolution, microbiology, biotechnology, animal behavior.")
        
        static let apPhys = ClassData(className: "AP Physics I (or C Mechanics) A&B", Teacher: "", credits: 2, preR: "Science 9, Honors Physics, Algebra II and enrollment in (or completion recommended) of Pre-Calc", description: "AP Physics is an introductory college-level physics course that completes the development of topics begun in or not treated in the Honors Physics course such as: constrained Newtonian systems, further development of Conservation Laws applied to energy and momentum of systems, Circular Motion, Center of Mass, Torque and Rotational Mechanics, Universal Law of Gravity and Orbital Motion. Through inquiry based learning and laboratory experiences, students will develop scientific critical thinking and reasoning skills and also learn how to use multilevel physics problem solving approaches. Data analysis of mathematical models for experimental questions are also developed. Students will be prepared for either the AP Physics 1 Exam and/or those students who have had Calculus will be given calculus based problems topics to prepare for the AP Physics C mechanics exam.")
        
        static let apEnviron = ClassData(className: "AP Environmental Science A&B", Teacher: "", credits: 2, preR: "Two semesters of high school laboratory science, including life science and physical science, along with at least one year of algebra.", description: "AP Environmental Science is an introductory college-level course in environmental science.  The class and exam focus on seven main topics: Earth Systems and Resources, The Living World, Populations, Land and Water Use, Energy Resources and Consumption, Pollution, and Global Change.  In this class you will explore and investigate the interrelationships of the natural world and analyze environmental problems, both natural and human-made. You’ll take part in laboratory investigations and field work.  Skills you will learn by taking this class include: 1. Explaining environmental concepts and processes; 2. Analyzing data, visual representations, and writings; 3. Applying quantitative methods in solving problems; 4. Proposing a solution for an environmental problem and supporting your idea with evidence; and 5. Analyzing a research study to identify a hypothesis. This course helps to prepare students interested in a possible career in the area of environmental science.")
        
        
        static let apChem = ClassData(className: "AP Chemistry", Teacher: "", credits: 2, preR: "Chemistry A&B or Honors Chemistry A&B and Pre-Calculus", description: "College Credit Available...This course is similar to a freshman college chemistry course and is designed to strengthen a student’s chemistry background. AP Chemistry will help prepare students who wish to take the AP Exam in May. Based on performance on the exam, students may be granted college credit and/or advanced placement at the discretion of the college or university. Course content in Term A includes: atoms, molecules, ions, solutions, gases, thermochemistry, atomic and molecular structure chemical bonding, liquids, and solids. Course content in Term B includes: chemical kinetics, equilibrium, acid-base systems, oxidation- reduction, solutions and colloids, chemical thermodynamics, and complex ions...Content is accessed in part through blended/online learning with elements of student control over time, place, path and/or pace. In addition content will also be acquired through peer learning, group work, and collaborative laboratory experiments.")
        
        static let apBio = ClassData(className: "AP Biology", Teacher: "", credits: 2, preR: "Biology (or Honors) A&B, AND Chemistry (or Honors) A&B", description: "College Credit Available...Advanced Placement Biology’s primary goal is to provide students with a challenging college level course and prepare the student for the national AP Biology Exam given in mid-May. Students enrolled in this course are encouraged to take the exam. Based on performance on the exam, students may be granted college credit and/or advanced placement at the discretion of the college or university. The course will include topics regularly covered in a college biology course for majors. The two main goals of AP Biology are to help students develop a conceptual framework for modern biology and an appreciation of science as a process.")
        
        static let advBio1 = ClassData(className: "Advanced Biology: Botany/Horticulture", Teacher: "", credits: 2, preR: "Biology A&B", description: "This two term course is offered in the spring. It introduces the student to the great variety of plants in the surrounding world and their significance both environmentally and economically. This course has a strong laboratory component and you must be ok with working outside and getting your hands dirty! Greenhouse work will be part of the course along with individual and/or group research. Numerous home landscaping and plant care topics will be covered.")
        
        
        static let advBio2 = ClassData(className: "Advanced Biology: Anatomy/Physlgy", Teacher: "", credits: 2, preR: "Biology A&B and Algebra I", description: "Advanced Biology is designed for students with a great interest in biology who wish to expand their knowledge in the areas of human anatomy and physiology. Students pursuing a health related or medical career may be particularly interested in this class. In term A, living structures will be studied in depth from the cellular level through the macroscopic level; special emphasis is placed on malformations, malfunctions, and diseases. The integumentary, skeletal, muscular, digestive, circulatory and immune systems are covered. Mini-units are also done on medical terms, the history of medicine, and alternative forms of medicine. Term B continues our study of living structures as we learn about the respiratory, endocrine, urinary, reproductive, nervous, and special senses. In addition, an investigative research project related to a controversial issue in medicine is done as well as a formal lab write-up. Systematic dissection of a fetal pig occurs throughout both terms.")
        
        
        
        
        
        
        
        
        
        static let advHeritageSpanish = ClassData(className: "Adv Comp&Comm Heritage Spanish A&B", Teacher: "", credits: 2, preR: "Spanish spoken in the home", description: "This course is designed for students who speak Spanish in the home and/or are fluent Spanish speakers. In this course, students are able to develop their linguistic ability in association with their written and comprehensive skills. Furthermore, emphasis is also placed on the subjects of communication and Latin American history. This course prepares students for the Bilingual Seal exam, in which they can earn college credit.")
        
        static let advSpanishImmersion3 = ClassData(className: "Advanced Spanish Immersion 3", Teacher: "", credits: 2, preR: "Spanish Language Arts 8 AND Grade 8 teacher recommendation", description: "This course is designed for Spanish immersion students entering high school with attention to enhanced literacy, pronunciation, writing skills, grammar polish, cultural awareness of Spanish speaking countries and transition to Advanced Spanish Immersion 4 and the rigor of college-level courses that follow.")
        
        static let advancedSpanish3 = ClassData(className: "Advanced Spanish Immersion 3", Teacher: "", credits: 2, preR: "Spanish Language Arts 8 AND Grade 8 teacher recommendation", description: "This course is designed for Spanish immersion students entering high school with attention to enhanced literacy, pronunciation, writing skills, grammar polish, cultural awareness of Spanish speaking countries and transition to Advanced Spanish Immersion 4 and the rigor of college-level courses that follow.")
        
        static let advancedSpanish4 = ClassData(className: "Advanced Spanish Immersion 4", Teacher: "", credits: 2, preR: "Advanced Spanish Immersion 3", description: "This course is designed for continuing Spanish immersion students at the high school level, who have successfully completed Advanced Spanish Immersion 3 , with attention to enhanced literacy, pronunciation, writing skills, grammar polish, and cultural awareness of Spanish speaking countries and transition to the rigor of college level courses to follow.")
        
        static let apSpanishLitandCulture = ClassData(className: "AP Spanish Lit and Culture", Teacher: "", credits: 2, preR: "Spanish 6 / SPAN 1004", description: "Students read and analyze Spanish literature from various Spanish speaking countries. The historical period spans from medieval to modern times. In the course students continue to develop proficiencies across the full range of the modes of communication (interpersonal, presentational, and interpretive), honing their critical reading and analytical writing skills. Besides reading, students study the historical context in which the work was made, and they analyze how historical context affects perspective and style of the work. Part of the course requires students to analyze in writing their observations of theme, style, and historical influences on the work. There are 1-2 hours of homework for the course each night, weekly assessments to monitor progress and periodic writing assessments.")
        
        static let americanSignLanguage1 = ClassData(className: "American Sign Language 1 A&B", Teacher: "", credits: 2, preR: "None", description: "Students will learn the basics for communication with deaf individuals. ASL is a visual language and requires participants to maintain eye contact while communicating. The course includes receptive and expressive readiness activities, sign vocabulary, basic rules of grammar, finger spelling, conversational behaviors, and various aspects of Deaf culture. Receptive and expressive sign vocabulary building, introductory conversation, and short narratives are featured.")
        
        static let asl2 = ClassData(className: "American Sign Language 2 A&B", Teacher: "", credits: 2, preR: "American Sign Language 1 A&B - a grade of “C” or better is recommended", description: "Students will continue to learn communication with deaf individuals. The course includes more advanced receptive and expressive activities, sign vocabulary, ASL grammatical structure, finger spelling, conversational behaviors, and various aspects of Deaf culture. Receptive and expressive sign vocabulary building, conversations, short stories and narratives are featured.")
        
        static let asl3 = ClassData(className: "American Sign Language 3 A&B", Teacher: "", credits: 2, preR: "American Sign Language 2 A&B - a grade of “C” or better is recommended.", description: "Students will continue to learn how to communicate with deaf individuals. The course includes advanced receptive and expressive activities, advanced sign vocabulary, sophisticated ASL grammatical structures, conversation behaviors, and various aspects of Deaf culture.")
        
        static let Chinese1 = ClassData(className: "Chinese 1 A&B", Teacher: "老师", credits: 2, preR: "没有", description: "This course is designed for students with little or no background in the target language. (To strengthen skills before Level 2, this course is also recommended for students who earned less than 75% in 7th & 8th grade.) The major emphasis in this course will be on the development of listening and speaking skills. Students will also begin to read and write using basic language structures and investigate relevant cultural traditions.")
        
        static let chinese2 = ClassData(className: "Chinese 2 A&B", Teacher: "老师", credits: 2, preR: "中文一 A&B or two years of 7th & 8th grade language study (recommended grade of 75% or higher), or teacher recommendation", description: "In this semester long course, students will continue to learn the features of language necessary for simple communication in varied applications. In the target language, they will comprehend spoken and written information (including the use of Chinese characters in Chinese II) and communicate simple information. In addition, students will recognize and identify relevant cultural traditions.")
        
        static let chinese3 = ClassData(className: "Chinese 3 A&B", Teacher: "老师", credits: 2, preR: "中文二 A&B", description: "In this semester-long course, students will continue to learn the features of language necessary for basic communication in varied applications. In the target language, students will comprehend spoken and written information and communicate basic information. They will continue to recognize and identify relevant cultural traditions.")
        
        static let chinese4 = ClassData(className: "Chinese 4 A&B", Teacher: "老师", credits: 2, preR: "中文三 A&B", description: "In this semester-long course, students will continue to learn the features of language necessary for communication in more complicated applications. In the target language, they will comprehend spoken and written information and communicate more complicated information. They will continue to recognize relevant cultural traditions.")
        
        static let chinese5 = ClassData(className: "Chinese 5 A&B", Teacher: "老师", credits: 2, preR: "中文四 A&B", description: "In this semester-long course, students will learn the features of language necessary for communication in more complicated applications. In Chinese, they will comprehend spoken and written information and communicate complex information. They will read and write Chinese characters and recognize Chinese cultural traditions.")
        
        static let french1 = ClassData(className: "French 1 A&B", Teacher: "", credits: 2, preR: "None", description: "This course is designed for students with little or no background in the target language. (To strengthen skills before Level 2, this course is also recommended for students who earned less than 75% in 7th & 8th grade.) The major emphasis in this course will be on the development of listening and speaking skills. Students will also begin to read and write using basic language structures and investigate relevant cultural traditions. ")
        
        static let french2 = ClassData(className: "French 2 A&B", Teacher: "", credits: 2, preR: "French 1 A&B or two years of 7th & 8th grade language study (recommended grade of 75% or higher), or teacher recommendation", description: "In this semester long course, students will continue to learn the features of language necessary for simple communication in varied applications. In the target language, they will comprehend spoken and written information and communicate simple information. In addition, students will recognize and identify relevant cultural traditions.")
        
        static let french3 = ClassData(className: "French 3 A&B", Teacher: "", credits: 2, preR: "French 2 A&B", description: "In this semester-long course, students will continue to learn the features of language necessary for basic communication in varied applications. In the target language, students will comprehend spoken and written information and communicate basic information. They will continue to recognize and identify relevant cultural traditions.")
        
        static let french4 = ClassData(className: "French 4 A&B", Teacher: "", credits: 2, preR: "French 3 A&B", description: "n this semester-long course, students will continue to learn the features of language necessary for communication in more complicated applications. In the target language, they will comprehend spoken and written information and communicate more complicated information. They will continue to recognize relevant cultural traditions.")
        
        static let french5 = ClassData(className: "French 5 A&B", Teacher: "", credits: 2, preR: "French 4 A&B...5 Univ of MN College Credits Available", description: "Students enrolling in this course have the option of taking this course for college credit in collaboration with the University of Minnesota’s College in the Schools program. Students will earn 2 EPHS credits and have the option of earning five University of Minnesota credits... This course will follow the curriculum of 1003 University of Minnesota course in the target language. Upon successful completion of this course, students who register for the college credit will earn 5 University of Minnesota credits and an official transcript. Students should anticipate the rigor and challenge associated with a university course.  Evaluations will include written and oral exams, formal compositions, daily homework and participation. Excessive absences are not allowed per the University’s requirements.")
        
        static let french6 = ClassData(className: "French 6 A&B", Teacher: "", credits: 2, preR: "French 5 / FREN 1003", description: "Students enrolling in this course have the option of taking this course for college credit via dual enrollment with the University of Minnesota’s College in the Schools program. Students will earn 2 EPHS credits and have the option of earning five University of Minnesota credits...This course will follow the curriculum of 1004 University of Minnesota course in the target language.  Upon successful completion of this course, students who register for the college credit will earn 5 University of Minnesota credits and an official transcript.  Students should anticipate the rigor and challenge associated with a university course. Evaluations will include written and oral exams, formal compositions, daily homework, and participation. Excessive absences are not allowed per the University’s requirements.")
        
        static let german1 = ClassData(className: "German 1 A&B", Teacher: "", credits: 2, preR: "None", description: "This course is designed for students with little or no background in the target language. (To strengthen skills before Level 2, this course is also recommended for students who earned less than 75% in 7th & 8th grade.) The major emphasis in this course will be on the development of listening and speaking skills. Students will also begin to read and write using basic language structures and investigate relevant cultural traditions.")
        
        static let german2 = ClassData(className: "German 2 A&B", Teacher: "", credits: 2, preR: "German 1 A&B or two years of 7th & 8th grade language study (recommended grade of 75% or higher), or teacher recommendation", description: "In this semester long course, students will continue to learn the features of language necessary for simple communication in varied applications. In the target language, they will comprehend spoken and written information and communicate simple information. In addition, students will recognize and identify relevant cultural traditions.")
        
        static let german3 = ClassData(className: "German 3 A&B", Teacher: "", credits: 2, preR: "German 2 A&B", description: "In this semester-long course, students will continue to learn the features of language necessary for basic communication in varied applications. In the target language, students will comprehend spoken and written information and communicate basic information. They will continue to recognize and identify relevant cultural traditions.")
        
        static let german4 = ClassData(className: "German 4 A&B", Teacher: "", credits: 2, preR: "German 3 A&B", description: "College Credit Available.. Students enrolling in this course have the option of taking this course for college credit in collaboration with the University of Minnesota’s College in the Schools program. Students will earn 2 EPHS credits and have the option of earning five University of Minnesota credits... This course will follow the curriculum of 1003 University of Minnesota course in the target language. Upon successful completion of this course, students who register for the college credit will earn 5 University of Minnesota credits and an official transcript. Students should anticipate the rigor and challenge associated with a university course. Evaluations will include written and oral exams, formal compositions, daily homework and participation. Excessive absences are not allowed per the University’s requirements.")
        
        static let german5 = ClassData(className: "German 5 A&B", Teacher: "", credits: 2, preR: "German 4 / CIS 1003", description: "College Credit Available...Students enrolling in this course have the option of taking this course for college credit in collaboration with the University of Minnesota’s College in the Schools program. Students will earn 2 EPHS credits and have the option of earning five University of Minnesota credits... This course will follow the curriculum of 1004 University of Minnesota course in the target language. Upon successful completion of this course, students who register for the college credit will earn 5 University of Minnesota credits and an official transcript. Students should anticipate the rigor and challenge associated with a university course. Evaluations will include written and oral exams, formal compositions, daily homework, and participation. Excessive absences are not allowed per the University’s requirements.")
        
        static let spanish1 = ClassData(className: "Spanish 1 A&B", Teacher: "", credits: 2, preR: "None", description: "This course is designed for students with little or no background in the target language. (To strengthen skills before Level 2, this course is also recommended for students who earned less than 75% in 7th & 8th grade.) The major emphasis in this course will be on the development of listening and speaking skills. Students will also begin to read and write using basic language structures and investigate relevant cultural traditions.")
        
        static let spanish2 = ClassData(className: "Spanish 2 A&B", Teacher: "", credits: 2, preR: "Spanish 1 A&B or two years of 7th & 8th grade language study (recommended grade of 75% or higher), or teacher recommendation", description: "In this semester long course, students will continue to learn the features of language necessary for simple communication in varied applications. In the target language, they will comprehend spoken and written information and communicate simple information. In addition, students will recognize and identify relevant cultural traditions.")
        
        static let spanish3 = ClassData(className: "Spanish 3 A&B", Teacher: "", credits: 2, preR: "Spanish 2 A&B", description: "In this semester-long course, students will continue to learn the features of language necessary for basic communication in varied applications. In the target language, students will comprehend spoken and written information and communicate basic information. They will continue to recognize and identify relevant cultural traditions.")
        
        static let spanish4 = ClassData(className: "Spanish 4 A&B", Teacher: "", credits: 2, preR: "Spanish 3 A&B", description: "In this semester-long course, students will continue to learn the features of language necessary for communication in more complicated applications. In the target language, they will comprehend spoken and written information and communicate more complicated information. They will continue to recognize relevant cultural traditions.")
        
        static let spanish5 = ClassData(className: "Spanish 5 A&B", Teacher: "", credits: 2, preR: "Spanish 4 A&B or Advanced Spanish Immersion 10 A&B", description: "5 Univ of MN College Credits Available...Students enrolling in this course have the option of taking this course for college credit via dual enrollment with the University of Minnesota’s “College in the Schools” program. Students will earn 2 EPHS credits and have the option of earning five University of Minnesota credits....This course will follow the curriculum of the University of Minnesota course, Spanish 1003, in the target language.  Upon successful completion of this course, students who register for the college credit will earn 5 University of Minnesota credits and an official transcript.   Students should anticipate the rigor and challenge associated with a university course.  Evaluations will include written and oral exams, formal compositions, daily homework and participation. Excessive absences are not allowed per the University’s requirements. ")
        
        static let spanish6 = ClassData(className: "Spanish 6 A&B", Teacher: "", credits: 2, preR: "Spanish 5 / SPAN 1003", description: "5 Univ of MN College Credits Available... Students enrolling in this course have the option of taking this course for college credit via dual enrollment with the University of Minnesota’s College in the Schools program. Students will earn 2 EPHS credits and have the option of earning five University of Minnesota credits...This course will follow the curriculum of Spanish 1004 University of Minnesota course in the target language.  Upon successful completion of this course, students who register for the college credit will earn 5 University of Minnesota credits and an official transcript. Students should anticipate the rigor and challenge associated with a university course. Evaluations will include written and oral exams, formal compositions, daily homework, and participation. Excessive absences are not allowed per the University’s requirements.")
        
        
        
        
        
        
        
        
        static let WorkExperienceClasses = [cee, ces, ephsee, ephses, fpess, ms, paseslab, so]
        
        
        static let cee = ClassData(className: "Community Employment Experience", Teacher: "", credits: 2, preR: "Community Employment Seminar", description: "This course offers an employment opportunity in the local community. Work experience teachers will help students taking this course in several ways, including finding job placements related to their goals and interests, coordinating transportation (if necessary), and assisting with job-related troubleshooting once placed at a jobsite. Students will receive guidance and support from their work experience teachers for the duration of the course.")
        
        static let ces = ClassData(className: "Community Employment Seminar", Teacher: "", credits: 2, preR: "None", description: "This course is designed to help you make a successful transition from school to work and will include topics related to post-secondary education and professional training, career readiness, work safety, labor laws, employability skills, and employee earnings and benefits. Opportunities to build career awareness and develop critical thinking, decision-making, and on-the-job problem solving are also primary components of the course. This course is the prerequisite to participating in the Community Employment Experience.")
        
        static let ephsee = ClassData(className: "EPHS Employment Experience", Teacher: "", credits: 2, preR: "EPHS Employment Seminar", description: "This course offers a paid or unpaid experience within EPHS. Job experiences will occur in the staff mailroom, media center, delivery dock, dish room, kitchen, and commons areas.  Basic work skills are applied, improved, and evaluated for future community placement. Students will follow the same expectations and etiquette that community businesses have for their employees, as this course is designed to lead to a community employment experience.")
        
        static let ephses = ClassData(className: "EPHS Employment Seminar", Teacher: "", credits: 2, preR: "Referral and qualifying placement", description: "This course is designed to prepare students for an initial work experience. Topics related to finding and keeping a job will be the major points of emphasis throughout the course. Students will receive a broad overview of many key concepts related to workplace success, including punctuality, attendance, teamwork, communication, and advocacy.  School staff will utilize employee handbooks and real-life examples to reinforce the importance of these essential skills.")
        
        
        static let fpess = ClassData(className: "Functional Pre-Employment Skills - Skinny", Teacher: "", credits: 2, preR: "Referral and qualifying placement", description: "Prepare for your future! Through this class, students will develop functional work skills through classroom activities and early employment experiences. Topics of focus include: teamwork, punctuality, communication skills (verbal and non-verbal), following instructions (one-step, multiple steps, written, and verbal) and workplace reading and math.")
        
        static let ms = ClassData(className: "Money Sense", Teacher: "", credits: 2, preR: "None", description: " It’s all about YOUR money!  You will learn what you really need to know about handling your finances.  Learn about budgeting, banking, insurance needs, tax preparation, credit, making large purchases, and more tips to help you manage your hard-earned money.")
        
        static let paseslab = ClassData(className: "PAES Lab", Teacher: "", credits: 2, preR: "Referral and qualifying placement", description: "The PAES (Practical Assessment Exploration System) program provides training in both employment and independent living skills. In this simulated work environment, students learn basic career skills, practice independence and advocacy, and discover. their interests in specific work areas and their job strengths. Curriculum focus is in 5 work areas: Business/Marketing, Computer/Technology, Construction/ Industrial, Processing/Production, and Consumer Service.")
        
        static let so = ClassData(className: "Service Occupations", Teacher: "", credits: 2, preR: "Referral  and qualifying placement    ", description: "This semester course includes classroom instruction and hands-on work-based experiences. The objective is for students to acquire a basic understanding of the skills required to perform a variety of tasks in several entry-level service occupations, including food preparation assistant, dining room attendant, dish room worker, laundry room worker, custodial aide, and outdoor grounds maintenance.")
        
        
        
        
        
        
        static let SocialClasses = [wordleHistoryII, worldHistoryI, usHistory, usGov, middleEast, sociology, gender, psych, humanGeo, econpublic, demon, cap, assFac, apModern, apush, apPoly, apPysch, apmacroe, aphumangeo, apcp, adjNation]
        
        
        
        
        static let wordleHistoryII = ClassData(className: "World History II: 1400 C.E. to Modern", Teacher: "", credits: 2, preR: "None", description: " World History II: 1400 to Modern is a comprehensive study of the development of civilization from the 1400’s to the rise of modern nationalism, imperialism, and revolutions that impacted the modern world.  The course will compare how cultures in all parts of the world including Africa, Asia and the Western hemisphere have adapted to an industrialized, interdependent world. Students in this course will analyze the various ways cultures adapt to change and the major influences that formulate the modern world.")
        
        static let worldHistoryI = ClassData(className: "World History I: Ancient to 1400 C.E.", Teacher: "", credits: 2, preR: "None", description: " World History I: Ancient to 1400 provides a comprehensive study of the development of civilization to the Middle Ages in Europe. This course will compare the emergence and development of cultures in all parts of the world including Africa, Asia, and the Western hemisphere. Students will analyze the geographic, economic, political, cultural, religious, and social systems that have emerged and influenced thought and behavior patterns in various cultures today. Topics include Prehistory, Mesopotamia, Egypt, India, China, Africa, Greece, Rome, and the Middle Ages.")
        
        static let usHistory = ClassData(className: "US History 10 A&B", Teacher: "", credits: 2, preR: "None", description: "This course is a thematic look at United States History from the early 1800’s through present day.  Unit topics include: American identity, expansionism, Constitution in crisis, role of the federal government and United States and the world. This course fulfills the State of Minnesota high school American History requirements.")
        
        static let usGov = ClassData(className: "US Government and Politics", Teacher: "", credits: 2, preR: "None", description: "In US Government & Politics, students learn and grow into informed members of the electorate capable of influencing the choices of local, state, and national governments. Students will analyze the Constitution and Bill of Rights in order to define their personal liberties and responsibilities in the United States. Additionally, students will study the role of the United States in the global community through an examination of historical trends and an analysis of current events. Most importantly, students will develop a personalized view of the political world and learn how to impact their communities as critical thinkers and engaged citizens.")
        
        static let middleEast = ClassData(className: "The Middle East: Crisis and Conflict", Teacher: "", credits: 1, preR: "None", description: "This course surveys the main political, social, economic, and intellectual currents of the broader Middle East during the 20th and 21st centuries. Areas of focus include Israel and the Palestinian territories, the Arab world, Turkey, and the rise of ISIS. Course emphasis is placed on answering fundamental questions regarding the historical background and development of current problems in the region. How has the region been formed and shaped by colonialism, political Islam, democratization, oil, revolution, and war? What are the core issues of regional conflicts and why has peace been so elusive? What are the possible outcomes of the ongoing turmoil unleashed by reform movements during the Arab Spring? Components of the course include current events analysis, debate and discussion, lecture, and an Israeli-Palestinian peace plan proposal.")
        
        static let sociology = ClassData(className: "Sociology", Teacher: "", credits: 2, preR: "None", description: "This course will help students gain a new understanding of human behavior and social relationships that apply in everyday life. Students will be introduced to the major sociological perspectives, as well as other basic concepts of sociology including; socialization, cultural norms, symbolic culture, sex & gender in society, class, race, and ethnicity. Methods that will be used to help students gain a better understanding of human behavior and social interactions include: blended/online learning that includes elements of student control over time, place, path and/or pace as well as large and small group discussions, hands on activities, speakers and self-reflection.")
        
        static let gender = ClassData(className: "Dynamics of Sex & Gender-ISJ", Teacher: "", credits: 1, preR: "None", description: "Ever wondered what makes something “feminine” in one culture but “masculine” in another? Are men really better at reading maps and women better at multi-tasking? Are the brains of men and women different? In this class we will study topics such as gender in sports, gender issues and inequalities around the globe, gender and the media, gender and bias, and ”brains, bodies & the binary”. By examining popular makings of masculinity, femininity, and sexuality we hope to broaden our “gender perspective” beyond traditional notions of femininity and masculinity. This class is an introduction to the emerging theories of gender fluidity around the world as it intersects with race, ethnicity, sexuality, policy, and culture. Students will engage with course content in part through blended/online learning that includes elements of student control over time, place, path and/or pace as well as group discussions/debate, hands on activities, and self-reflection.")
        
        static let psych = ClassData(className: "Psychology", Teacher: "", credits: 1, preR: "None", description: "This course offers a hands-on exploration of human behavior and mental processes. Pioneering and contemporary theories of psychology are studied and then applied to everyday situations. Mental illness, personality development, sleep / dreams, hypnosis / meditation, subliminal messages, sensory illusions, ESP, learning, and the brain are just a few of the topics that are examined. Active classroom experiments, demonstrations, and thoughtful discussion are all classroom tools used to better understand the science of human behavior.")
        
        static let humanGeo = ClassData(className: "Human Geography 9", Teacher: "", credits: 2, preR: "None", description: "Geography is divided into two main branches. Physical geography is the scientific study of natural features on the Earth’s surface. Human Geography studies the interrelationships between people, place, and environment. In this course, students will examine the culture, population, politics, urbanization, and agricultural practices in human societies. Project-based learning will provide choices and opportunities for each student to become more conscious-minded and culturally aware global citizens. In addition, students will read, research, and interpret information in order to understand the relationships between cultures, critically analyze events that have led to our existing societies, and offer creative solutions to current world issues.")
        
        static let econpublic = ClassData(className: "Economics and Public Policy", Teacher: "", credits: 1, preR: "None", description: "In a world of scarce resources, how is it determined what goods and services are made and who gets what? What causes an economy to do well or to fall into a recession? What is the proper role of government in managing economic issues and outcomes? In Economics and Public Policy, students will learn about price determination and markets,, income inequality, economic growth, inflation, unemployment, international trade issues, and government budget deficits and the national debt.  Additionally, the course provides a unified framework to address these issues by studying the impact of different policies, such as monetary and fiscal policies, on aggregate behavior. Students will utilize the tools and theory of economics to analyze and create solutions to public policy issues, both in the United States and around the world.")
        
        static let demon = ClassData(className: "Democratic Foundations (formerly Civics 9)", Teacher: "", credits: 1, preR: "None", description: "This course in civics focuses on student critical thinking skills within the context of the development, establishment and continuation of the American political system. Students learn about the rights and obligations of citizenship at the local, state, and national levels. Topics include: the three branches of government, relationships in government, amending the Constitution, and current issues in American democracy, as well as around the world. All students will access rigorous course content by engaging in simulations, debates, small & large group discussions, online learning, and analysis of current issues. Students will read material that is often above grade level.")
        
        static let cap = ClassData(className: "Combined AP US Government / AP Comparative Politics", Teacher: "", credits: 2, preR: "None", description: "College Credit Available. The student that sign up for this combined course will take both AP U.S. Government and AP Comparative Politics (see course descriptions above) on an every-other-day basis covering two terms. This combined course will offer the student additional enrichment opportunities such as books and salons that only an extended time format allows. This unique course gives students the opportunity to compare and contrast the American government with the international political systems covered in AP Comparative Politics. In addition, the overlap in course content and themes makes this combination a natural fit.")
        
        static let assFac = ClassData(className: "Assassination Fascination", Teacher: "", credits: 1, preR: "None", description: "From the Archduke Franz Ferdinand to that fateful day in Dallas 1963, it’s undeniable that few events in history have a more immediate transformational impact than assassinations. This course will analyze notable assassinations, their impact, and historical significance in the United States and world. Among the assassinations discussed will be Abraham Lincoln, John F. Kennedy, James Garfield, William McKinley, Martin Luther King, Jr., and Malcolm X along with some of the “almosts” such as Teddy Roosevelt, George Wallace, and Ronald Reagan.")
        
        static let apModern = ClassData(className: "AP World History: Modern", Teacher: "", credits: 2, preR: "None", description: "AP World History: Modern is an introductory college-level modern world history course. Students cultivate their understanding of world history from c. 1200 CE to the present through analyzing historical sources and learning to make connections and craft historical arguments as they explore concepts like humans and the environment, cultural developments and interactions, governance, economic systems, social interactions and organization, and technology and innovation.Students will read college-level materials for main ideas, analyze, synthesize, identify bias, and determine cause and effect. This class covers a significant quantity of material at a college level. Therefore, students should possess both a strong reading ability and broad vocabulary skills. In addition, students must demonstrate fluid and analytical writing and discerning critical thinking skills.  Emphasis placed on critical thinking skills will include analysis and interpretation of historical events and documents.")
        
        static let apush = ClassData(className: "AP US History 10 A/B/C (3 Terms)", Teacher: "", credits: 2, preR: "None", description: "College Credit Available. This course is equivalent to demands made by full-year introductory college courses in U.S. history.  Students learn to assess historical materials—their relevance to a given interpretive problem, reliability, and importance—and to weigh the evidence and interpretations presented in historical scholarship.  Students develop the skills necessary to arrive at conclusions on the basis of an informed judgment and to present reasons and evidence clearly and persuasively in essay format. The class details the development of the United States from pre-settlement through the present day. This course prepares students for the Advanced Placement Exam in May of each school year. This course fulfills the State of Minnesota high school American History requirement. Summer assignment is required.")
        
        static let apPoly = ClassData(className: "AP US Government", Teacher: "", credits: 2, preR: "None", description: "College Credit Available. The AP US Government course provides an analytical perspective on government and politics in the United States. This course involves both the study of general concepts used to interpret U.S. politics and the analysis of specific case studies. It also requires familiarity with the various institutions, groups, beliefs, and ideas that constitute U.S. political reality. Specifically the course covers the Constitutional Foundations, Political Theory and Beliefs, Development of Political Parties, Elections, Interest Groups and the Mass Media, the Formal Institutions of Government and Public Policy, and lastly Civil Liberties and Civil Rights.")
        
        static let apPysch = ClassData(className: "AP Psychology", Teacher: "", credits: 2, preR: "None", description: "College Credit Available. The AP Psychology course introduces students to the systematic and scientific study of human behavior and mental processes. While considering the psychologists and studies that have shaped the field, students explore and apply psychological theories, key concepts, and phenomena associated with such topics as the biological bases of behavior, sensation and perception, learning and cognition, motivation, developmental psychology, testing and individual differences, treatments of psychological disorders, and social psychology. Throughout the course, students employ psychological research methods, including ethical considerations, as they use the scientific method, evaluate claims and evidence, and effectively communicate ideas.")
        
        static let apmacroe = ClassData(className: "AP Macroeconomics", Teacher: "", credits: 1, preR: "None", description: "How’s the economy doing? How do we know? What can a government do to fix a bad economy? Should they? What are the issues with a high national debt? How big of an issue is it? These are such questions this college-level course in macroeconomics will consider and students will be able to offer insight grounded in scholarly study. This course places particular emphasis on the study of gross domestic product, unemployment, and inflation, and also develops students’ familiarity with the financial sector, fiscal and monetary policies, economic growth, international trade policies, and currency value determination. Moreover, students will be able to utilize macroeconomic theory and thinking skills to evaluate the roles a federal government and central bank play in a nation’s economy. This course prepares students to take the Advanced Placement exam.")
        
        static let aphumangeo = ClassData(className: "AP Human Geography 9", Teacher: "", credits: 2, preR: "None", description: "College Credit Available. AP Human Geography 9 is a two-term course that focuses on the processes and cause and effect relationships of human populations. Emphasis throughout the course is on the arrangement of patterns and conditions across the Earth’s surface, differences in scale, and cultural determinants influenced by global interaction and integration. Major themes of study include globalization, diffusion, integration, and interaction. This class covers a significant quantity of material at a very quick pace. As a result, students should possess both a strong reading ability and broad vocabulary skills. In addition, students should demonstrate fluid and analytical writing and discerning critical thinking skills.")
        
        static let apcp = ClassData(className: "AP Comparative Politics", Teacher: "", credits: 2, preR: "None", description: "College Credit Available. This class introduces students to major themes and concepts in political science and examines the governments and politics of the United Kingdom, Russia, China, Mexico, Nigeria, and Iran.  Specifically, the class focuses upon the following themes:  a) sources of public authority and political power; b) the citizen and the state; c) types of regimes and scope of government activity; and d) internal and external sources of political change.  Special focus is placed on the current political and economic issues of these countries.  To successfully complete this course, critical thinking, reasoned judgment and substantial reading are required on a daily basis.  This course prepares students for the Advanced Placement Exam in May of each year and fulfills the second half of the Minnesota State World History requirement.")
        
        static let adjNation = ClassData(className: "Adjudication Nation", Teacher: "", credits: 1, preR: "None", description: "This is a course on criminal law and justice in the United States. It is designed to give students an exposure to the law and the American legal system considering the perspective of the individuals involved - including accused criminals, litigants, prosecutors, judges and jury members. Topics within the course will include, but not be limited to, state and federal court systems, criminal and civil law, ethics and values, and an exploration of the history of and current issues around justice, law, and the legal system in the United States.")
        
        
        }







